import os
import logging
from datetime import datetime
from typing import Dict, Optional
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, cm
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY, TA_RIGHT
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Frame, PageTemplate
from reportlab.platypus import Table, TableStyle, Image, KeepTogether
from reportlab.lib import colors
from reportlab.pdfgen import canvas
from config.settings import settings

# Initialize logger
logger = logging.getLogger(__name__)


class CorporateDocTemplate(SimpleDocTemplate):
    """Custom document template with corporate header/footer"""
    
    def __init__(self, filename, **kwargs):
        SimpleDocTemplate.__init__(self, filename, **kwargs)
        
    def build(self, flowables, onFirstPage=None, onLaterPages=None, canvasmaker=canvas.Canvas):
        """Override to add custom page templates"""
        self._calc()
        frameT = Frame(self.leftMargin, self.bottomMargin, 
                      self.width, self.height - 1.5*cm, id='normal')
        
        self.addPageTemplates([
            PageTemplate(id='First', frames=frameT, onPage=self._corporate_header_footer),
            PageTemplate(id='Later', frames=frameT, onPage=self._corporate_header_footer)
        ])
        
        SimpleDocTemplate.build(self, flowables, canvasmaker=canvasmaker)
    
    def _corporate_header_footer(self, canvas, doc):
        """Add corporate-style header and footer to each page"""
        canvas.saveState()
        
        # Header - gradient bar effect
        canvas.setFillColorRGB(0.2, 0.3, 0.5)  # Corporate blue
        canvas.rect(doc.leftMargin - 20, doc.height + doc.bottomMargin + doc.topMargin - 30, 
                   doc.width + 40, 25, fill=1, stroke=0)
        
        canvas.setFillColorRGB(0.39, 0.40, 0.94)  # Accent purple
        canvas.rect(doc.leftMargin - 20, doc.height + doc.bottomMargin + doc.topMargin - 33, 
                   doc.width + 40, 3, fill=1, stroke=0)
        
        # Header text
        canvas.setFillColorRGB(1, 1, 1)
        canvas.setFont('Helvetica-Bold', 12)
        canvas.drawString(doc.leftMargin, doc.height + doc.bottomMargin + doc.topMargin - 20, 
                         "AI RESEARCH REPORT")
        
        # Confidential badge
        canvas.setFont('Helvetica', 8)
        canvas.drawRightString(doc.leftMargin + doc.width, 
                              doc.height + doc.bottomMargin + doc.topMargin - 20,
                              "CONFIDENTIAL - EXECUTIVE SUMMARY")
        
        # Footer - gradient bar
        canvas.setFillColorRGB(0.9, 0.9, 0.95)
        canvas.rect(doc.leftMargin - 20, doc.bottomMargin - 35, doc.width + 40, 30, fill=1, stroke=0)
        
        canvas.setFillColorRGB(0.39, 0.40, 0.94)
        canvas.rect(doc.leftMargin - 20, doc.bottomMargin - 35, doc.width + 40, 2, fill=1, stroke=0)
        
        # Footer text
        canvas.setFillColorRGB(0.3, 0.3, 0.3)
        canvas.setFont('Helvetica', 9)
        canvas.drawString(doc.leftMargin, doc.bottomMargin - 25, 
                         f"Generated by AI Research Agent | {datetime.now().strftime('%B %Y')}")
        
        # Page number
        canvas.drawRightString(doc.leftMargin + doc.width, doc.bottomMargin - 25,
                              f"Page {doc.page}")
        
        canvas.restoreState()


class PDFGenerator:
    """Enterprise-grade PDF report generator with corporate styling"""
    
    def __init__(self):
        # Ensure reports directory exists
        os.makedirs(settings.REPORTS_PATH, exist_ok=True)
        logger.info(f"PDFGenerator initialized with reports path: {settings.REPORTS_PATH}")
        
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()
        logger.debug("Custom PDF styles configured")
    
    def _setup_custom_styles(self):
        """Setup premium corporate paragraph styles"""
        
        # Cover title style - large, bold, professional
        self.styles.add(ParagraphStyle(
            name='CoverTitle',
            parent=self.styles['Heading1'],
            fontSize=32,
            textColor=colors.HexColor('#1a1a2e'),
            spaceAfter=20,
            alignment=TA_CENTER,
            fontName='Helvetica-Bold',
            leading=38
        ))
        
        # Subtitle - elegant accent
        self.styles.add(ParagraphStyle(
            name='Subtitle',
            parent=self.styles['Normal'],
            fontSize=14,
            textColor=colors.HexColor('#6366f1'),
            spaceAfter=40,
            alignment=TA_CENTER,
            fontName='Helvetica',
            leading=18
        ))
        
        # Executive summary header
        self.styles.add(ParagraphStyle(
            name='ExecutiveHeader',
            parent=self.styles['Heading1'],
            fontSize=22,
            textColor=colors.HexColor('#2c3e50'),
            spaceAfter=16,
            spaceBefore=20,
            fontName='Helvetica-Bold',
            borderWidth=2,
            borderColor=colors.HexColor('#6366f1'),
            borderPadding=8,
            backColor=colors.HexColor('#f8f9ff')
        ))
        
        # Section headers - corporate blue
        self.styles.add(ParagraphStyle(
            name='SectionHeader',
            parent=self.styles['Heading2'],
            fontSize=16,
            textColor=colors.HexColor('#1e40af'),
            spaceAfter=12,
            spaceBefore=20,
            fontName='Helvetica-Bold',
            borderWidth=0,
            leftIndent=0,
            borderPadding=6,
            backColor=colors.HexColor('#eff6ff')
        ))
        
        # Subsection headers
        self.styles.add(ParagraphStyle(
            name='SubsectionHeader',
            parent=self.styles['Heading3'],
            fontSize=13,
            textColor=colors.HexColor('#4338ca'),
            spaceAfter=8,
            spaceBefore=12,
            fontName='Helvetica-Bold'
        ))
        
        # Body text - professional, readable
        self.styles.add(ParagraphStyle(
            name='CustomBody',
            parent=self.styles['BodyText'],
            fontSize=11,
            alignment=TA_JUSTIFY,
            spaceAfter=10,
            leading=16,
            textColor=colors.HexColor('#374151')
        ))
        
        # Key finding style - highlighted
        self.styles.add(ParagraphStyle(
            name='KeyFinding',
            parent=self.styles['BodyText'],
            fontSize=11,
            alignment=TA_LEFT,
            spaceAfter=10,
            leading=15,
            leftIndent=20,
            textColor=colors.HexColor('#1f2937'),
            bulletIndent=10,
            fontName='Helvetica'
        ))
        
        # Source citation style
        self.styles.add(ParagraphStyle(
            name='Citation',
            parent=self.styles['BodyText'],
            fontSize=9,
            alignment=TA_LEFT,
            spaceAfter=8,
            leading=12,
            leftIndent=15,
            textColor=colors.HexColor('#6b7280'),
            fontName='Helvetica'
        ))
        
        # Metadata style
        self.styles.add(ParagraphStyle(
            name='Metadata',
            parent=self.styles['Normal'],
            fontSize=10,
            textColor=colors.HexColor('#9ca3af'),
            spaceAfter=6,
            alignment=TA_CENTER,
            fontName='Helvetica'
        ))
    
    async def generate_report(
        self,
        research_data: Dict,
        report_id: str,
        include_sources: bool = True
    ) -> str:
        """
        Generate premium corporate PDF report from research data
        
        Args:
            research_data: Research data dictionary
            report_id: Unique report identifier
            include_sources: Whether to include sources
            
        Returns:
            Path to generated PDF file
        """
        try:
            logger.info(f"Generating enterprise PDF report: {report_id}")
            
            # Create filename
            filename = f"report_{report_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
            filepath = os.path.join(settings.REPORTS_PATH, filename)
            
            logger.debug(f"PDF filepath: {filepath}")
            
            # Create corporate PDF document
            doc = CorporateDocTemplate(
                filepath,
                pagesize=letter,
                rightMargin=1*inch,
                leftMargin=1*inch,
                topMargin=1.2*inch,
                bottomMargin=1*inch,
                title=f"Research Report - {research_data.get('topic', 'Analysis')}",
                author="AI Research Agent - Powered by Gemini 2.5 Flash"
            )
            
            # Build content
            story = []
            
            # === COVER PAGE ===
            story.append(Spacer(1, 1.5*inch))
            
            # Main title
            title = research_data.get('topic', 'Research Report')
            story.append(Paragraph(title.upper(), self.styles['CoverTitle']))
            story.append(Spacer(1, 0.2*inch))
            
            # Subtitle
            story.append(Paragraph(
                "Executive Intelligence Report",
                self.styles['Subtitle']
            ))
            story.append(Spacer(1, 1*inch))
            
            # Metadata box
            created_at = research_data.get('created_at', datetime.now())
            if isinstance(created_at, str):
                created_at = datetime.fromisoformat(created_at.replace('Z', '+00:00'))
            
            metadata_data = [
                ['Report ID:', research_data.get('research_id', 'N/A')],
                ['Generated:', created_at.strftime('%B %d, %Y')],
                ['Time:', created_at.strftime('%I:%M %p %Z')],
                ['AI Model:', 'Google Gemini 2.5 Flash'],
                ['Classification:', 'CONFIDENTIAL']
            ]
            
            metadata_table = Table(metadata_data, colWidths=[2*inch, 3.5*inch])
            metadata_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#eff6ff')),
                ('BACKGROUND', (1, 0), (1, -1), colors.white),
                ('TEXTCOLOR', (0, 0), (-1, -1), colors.HexColor('#1f2937')),
                ('ALIGN', (0, 0), (0, -1), 'RIGHT'),
                ('ALIGN', (1, 0), (1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#cbd5e1')),
                ('ROWBACKGROUNDS', (0, 0), (-1, -1), [colors.HexColor('#f8fafc'), colors.white]),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('LEFTPADDING', (0, 0), (-1, -1), 12),
                ('RIGHTPADDING', (0, 0), (-1, -1), 12),
                ('TOPPADDING', (0, 0), (-1, -1), 8),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ]))
            story.append(metadata_table)
            
            story.append(Spacer(1, 0.5*inch))
            
            # Disclaimer
            disclaimer = Paragraph(
                "<i>This report contains confidential information generated by advanced AI analysis. "
                "The insights provided are based on comprehensive research from verified sources. "
                "For internal use only.</i>",
                self.styles['Metadata']
            )
            story.append(disclaimer)
            
            story.append(PageBreak())
            
            # === EXECUTIVE SUMMARY ===
            story.append(Spacer(1, 0.3*inch))
            story.append(Paragraph("EXECUTIVE SUMMARY", self.styles['ExecutiveHeader']))
            story.append(Spacer(1, 0.15*inch))
            
            summary = research_data.get('summary', 'No summary available.')
            story.append(Paragraph(summary, self.styles['CustomBody']))
            story.append(Spacer(1, 0.3*inch))
            
            # === KEY FINDINGS ===
            key_findings = research_data.get('key_findings', [])
            if key_findings:
                story.append(Paragraph("KEY FINDINGS & INSIGHTS", self.styles['SectionHeader']))
                story.append(Spacer(1, 0.1*inch))
                
                # Create findings table with colored bullets
                findings_data = []
                for idx, finding in enumerate(key_findings, 1):
                    bullet = Paragraph(
                        f'<font color="#6366f1" size="14"><b>●</b></font>',
                        self.styles['KeyFinding']
                    )
                    text = Paragraph(
                        f'<b>Finding {idx}:</b> {finding}',
                        self.styles['KeyFinding']
                    )
                    findings_data.append([bullet, text])
                
                findings_table = Table(findings_data, colWidths=[0.3*inch, 5.7*inch])
                findings_table.setStyle(TableStyle([
                    ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                    ('LEFTPADDING', (0, 0), (-1, -1), 0),
                    ('RIGHTPADDING', (0, 0), (-1, -1), 0),
                    ('TOPPADDING', (0, 0), (-1, -1), 4),
                    ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
                ]))
                story.append(findings_table)
                story.append(Spacer(1, 0.3*inch))
            
            # === DETAILED ANALYSIS ===
            detailed_analysis = research_data.get('detailed_analysis', '')
            if detailed_analysis:
                story.append(Paragraph("COMPREHENSIVE ANALYSIS", self.styles['SectionHeader']))
                story.append(Spacer(1, 0.15*inch))
                
                if isinstance(detailed_analysis, dict):
                    # Process each section with proper formatting
                    section_order = [
                        ('executive_overview', 'Executive Overview'),
                        ('market_analysis', 'Market Analysis & Dynamics'),
                        ('strategic_insights', 'Strategic Insights & Opportunities'),
                        ('risk_assessment', 'Risk Assessment & Mitigation'),
                        ('implementation_roadmap', 'Implementation Roadmap'),
                        ('financial_implications', 'Financial Impact Analysis'),
                        ('future_outlook', 'Future Outlook & Predictions'),
                        ('competitive_intelligence', 'Competitive Intelligence')
                    ]
                    
                    for key, title in section_order:
                        if key in detailed_analysis and detailed_analysis[key]:
                            story.append(Paragraph(title, self.styles['SubsectionHeader']))
                            
                            # Split content into paragraphs
                            content = str(detailed_analysis[key])
                            paragraphs = content.split('\n\n') if '\n\n' in content else [content]
                            
                            for para in paragraphs:
                                if para.strip():
                                    story.append(Paragraph(para.strip(), self.styles['CustomBody']))
                                    story.append(Spacer(1, 0.1*inch))
                            
                            story.append(Spacer(1, 0.2*inch))
                else:
                    # Split by paragraphs for better formatting
                    paragraphs = str(detailed_analysis).split('\n\n')
                    for para in paragraphs:
                        if para.strip():
                            story.append(Paragraph(para.strip(), self.styles['CustomBody']))
                            story.append(Spacer(1, 0.1*inch))
                
                story.append(Spacer(1, 0.2*inch))
            
            # === SOURCES & REFERENCES ===
            if include_sources:
                sources = research_data.get('sources', [])
                if sources:
                    story.append(PageBreak())
                    story.append(Spacer(1, 0.3*inch))
                    story.append(Paragraph("SOURCES & REFERENCES", self.styles['SectionHeader']))
                    story.append(Spacer(1, 0.15*inch))
                    
                    logger.debug(f"Adding {len(sources)} sources to PDF")
                    
                    # Format sources with better styling
                    for idx, source in enumerate(sources, 1):
                        source_para = Paragraph(
                            f'<b>[{idx}]</b> {source}',
                            self.styles['Citation']
                        )
                        story.append(source_para)
                        story.append(Spacer(1, 0.05*inch))
            
            # Build PDF with corporate template
            logger.debug("Building enterprise PDF document...")
            doc.build(story)
            
            file_size = os.path.getsize(filepath)
            logger.info(f"Enterprise PDF generated successfully: {filename} ({file_size} bytes)")
            
            return filepath
            
        except Exception as e:
            logger.error(f"PDF generation failed for {report_id}: {str(e)}", exc_info=True)
            raise Exception(f"PDF generation failed: {str(e)}")


# Singleton instance
pdf_generator = PDFGenerator()
